# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm i
    npm run lint
    npm test
    npm run build
  displayName: 'Build, test ReactTS client'
  name: 'ReactTSBuild'
  workingDirectory: 'menu-reactts'
  failOnStderr: false
